### ISSUE TITLE
What is special about this Distro?

### ISSUE THREAD

**Issue by revoltez** [MILOUDIAS/FennecOS#8]
From the Readme; there are instructions on how to build it, which looks like an automated script for LFS, but what does it contain that makes the distro unique?

and why not distribute iso images directly? most users won't be interested in building it from scratch!

**Comment by MILOUDIAS** [comment]
This distro is in its very early stages; I'm still developing its foundation.

**Comment by MILOUDIAS** [comment]
In the near future, I will provide ready-to-use ISO images with a GUI installer, DE and a display manager.
